# 多节点高可用模式 - 节点2
spring:
  profiles: peer2
  application:
    name: registry
server:
  port: 10002
eureka:
  server:
    #enableSelfPreservation: false
  instance:
    hostname: peer2
  client:
    # 由于application.yml配置单节点模式, 本地运行的时候需要覆盖配置
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/,http://peer3:1003/eureka/