spring:
  application:
    name: provider
server:
  port: 2006
eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      # 单注册中心
      defaultZone: http://localhost:1006/eureka/
      # 多注册中心
      # defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/,http://peer3:1003/eureka/